---
title: "Problem Set 6"
author: "Reid McIlroy-Young"
date: "February 20, 2017"
output: html_document
---

``` {r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, warning = FALSE)

library(ggplot2)
library(tidyverse)
library(tidyverse)
library(modelr)
library(broom)
library(forcats)
library(tidyverse)
library(modelr)
library(broom)
library(forcats)
library(pROC)
```

``` {r, Q 1.1.1}
targetFile <- "data/mental_health.csv"
data <- read.csv(targetFile)

qplot(vote96, data=data, geom="histogram", main = "Voter turnout", binwidth = 1, xlab = 'Number of times voted', ylab ='Count') +
  scale_x_discrete(limits=c(0,1))

probVote <- sum(data$vote96, na.rm=TRUE) / length(data$vote96)

sprintf("%.2f", probVote)
```


``` {r, Q 1.1.2}

ggplot(data, aes(mhealth_sum, vote96)) +
  geom_point() +
  geom_smooth(method = lm) +
  labs(title="Mental health score vs number of times voted",  x ="Mental health score", y = "Number of times voted") +
  scale_y_continuous(limits = c(0, 1))
```

``` {r, Q 1.2.1}
svLogit = glm(vote96 ~ mhealth_sum, data = data, family = binomial)
summary(svLogit)
```

``` {r, Q 1.2.2}
#From notes
logit2prob <- function(x){
  exp(x) / (1 + exp(x))
}

prob2odds <- function(x){
  x / (1 - x)
}

prob2logodds <- function(x){
  log(prob2odds(x))
}

vote96_pred <- add_predictions(data, svLogit) 
vote96_pred <- mutate(vote96_pred, prob = logit2prob(pred))
vote96_pred <- mutate(vote96_pred, odds = prob2odds(prob))
vote96_pred <- na.omit(vote96_pred)
  
ggplot(vote96_pred, aes(mhealth_sum, pred)) +
  geom_line(color = "orange", size = 1) +
  labs(
    title = "Log odds of voting vs Mental Health rating",
    x = "Mental Health rating",
    y = "Log-odds of voting")
```


``` {r, Q 1.2.3}
ggplot(vote96_pred, aes(mhealth_sum, odds)) +
  geom_line(color = "orange", size = 1) +
  labs(
    title = "Odds of voting vs Mental Health rating",
    x = "Mental Health rating",
    y = "Odds of voting")
```

``` {r, Q 1.2.4}
ggplot(vote96_pred, aes(mhealth_sum, prob)) +
  geom_line(color = "orange", size = 1) +
  labs(
    title = "Prob of voting vs Mental Health rating",
    x = "Mental Health rating",
    y = "Prob of voting")

grid <- data_grid(data, mhealth_sum)
grid <- add_predictions(grid, svLogit)
grid <- mutate(grid, prob = logit2prob(pred))

diff12 <- grid[3,] - grid[2,]
diff12 <- diff12$prob
diff56 <- grid[7,] - grid[6,]
diff56 <- diff56$prob
```


``` {r, Q 1.2.5}
#From notes
PRE <- function(model){
  # get the actual values for y from the data
  y <- model$y
  
  # get the predicted values for y from the model
  y.hat <- round(model$fitted.values)
  
  # calculate the errors for the null model and your model
  E1 <- sum(y != median(y))
  E2 <- sum(y != y.hat)
  
  # calculate the proportional reduction in error
  PRE <- (E1 - E2) / E1
  return(PRE)
}


vote96_accuracy <- add_predictions(data, svLogit)
vote96_accuracy <- mutate(vote96_accuracy, pred = as.numeric(logit2prob(pred) > .5))

ac <- mean(vote96_accuracy$vote96 == vote96_accuracy$pred, na.rm = TRUE)

pre <- PRE(svLogit)

auc_val <- auc(vote96_accuracy$vote96, vote96_accuracy$pred)
```

``` {r, Q 1.3.2}
mvLogit <- glm(vote96 ~ . , data = data, family = binomial)

summary(mvLogit)
```


``` {r Q 2.1.1}
targetFile <- "data/gss2006.csv"
data <- na.omit(read.csv(targetFile))

tvLogit <- glm(tvhours ~ . , data = data, family = poisson)
```