---
title: "Problem set #6: Generalized linear models"
author: "MACS 30100 - Perspectives on Computational Modeling"
date: "**Due Monday February 20th at 11:30am**"
output:
  github_document:
    toc: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE)
```

# Part 1: Modeling voter turnout

An important question in American politics is why do some people participate in the political process, while others do not? Participation has a direct impact on outcomes -- if you fail to participate in politics, the government and political officials are less likely to respond to your concerns. Typical explanations focus on a resource model of participation -- individuals with greater resources, such as time, money, and civic skills, are more likely to participate in politics. One area of importance is understanding voter turnout, or why people participate in elections. Using the resource model of participation as a guide, we can develop several expectations. First, women, who more frequently are the primary caregiver for children and earn a lower income, are less likely to participate in elections than men. Second, older Americans, who typically have more time and higher incomes available to participate in politics, should be more likely to participate in elections than younger Americans. Finally, individuals with more years of education, who are generally more interested in politics and understand the value and benefits of participating in politics, are more likely to participate in elections than individuals with fewer years of education.

While these explanations have been repeatedly tested by political scientists, an emerging theory assesses an individual's mental health and its effect on political participation.^[[Ojeda, C. (2015). Depression and political participation. *Social Science Quarterly*, 96(5), 1226-1243.](http://onlinelibrary.wiley.com.proxy.uchicago.edu/doi/10.1111/ssqu.12173/abstract)] Depression increases individuals' feelings of hopelessness and political efficacy, so depressed individuals will have less desire to participate in politics. More importantly to our resource model of participation, individuals with depression suffer physical ailments such as a lack of energy, headaches, and muscle soreness which drain an individual's energy and requires time and money to receive treatment. For these reasons, we should expect that individuals with depression are less likely to participate in election than those without symptoms of depression.

The 1998 General Social Survey included several questions about the respondent's mental health. `mental_health.csv` reports several important variables from this survey.

* `vote96` - 1 if the respondent voted in the 1996 presidential election, 0 otherwise
* `mhealth_sum` - index variable which assesses the respondent's mental health, ranging from 0 (an individual with no depressed mood) to 9 (an individual with the most severe depressed mood)^[The variable is an index which combines responses to four different questions: "In the past 30
days, how often did you feel: 1) so sad nothing could cheer you up, 2) hopeless, 3) that everything was an effort, and 4) worthless?" Valid responses are none of the time, a little of the time, some of the time, most of the time, and all of the time.]
* `age` - age of the respondent
* `educ` - Number of years of formal education completed by the respondent
* `black` - 1 if the respondent is black, 0 otherwise
* `female` - 1 if the respondent is female, 0 if male
* `married` - 1 if the respondent is currently married, 0 otherwise
* `inc10` - Family income, in \$10,000s

## Describe the data (1 point)

1. Plot a histogram of voter turnout. Make sure to give the graph a title and proper $x$ and $y$-axis labels. What is the unconditional probability of a given individual turning out to vote?
1. Generate a scatterplot of the relationship between mental health and observed voter turnout and overlay a linear smoothing line. What information does this tell us? What is problematic about this linear smoothing line?

## Basic model (3 points)

Estimate a logistic regression model of the relationship between mental health and voter turnout.

1. Is the relationship between mental health and voter turnout statistically and/or substantively significant?
1. Interpret the estimated parameter for mental health in terms of log-odds. Generate a graph of the relationship between mental health and the log-odds of voter turnout.
1. Interpret the estimated parameter for mental health in terms of odds. Generate a graph of the relationship between mental health and the odds of voter turnout.
1. Interpret the estimated parameter for mental health in terms of probabilities. Generate a graph of the relationship between mental health and the probability of voter turnout. What is the first difference for an increase in the mental health index from 1 to 2? What about for 5 to 6?
1. Estimate the accuracy rate, proportional reduction in error (PRE), and the AUC for this model. Do you consider it to be a good model?

## Multiple variable model (3 points)

Using the other variables in the dataset, derive and estimate a multiple variable logistic regression model of voter turnout.

1. Write out the three components of the GLM for your specific model of interest. This includes the
    * Probability distribution (random component)
    * Linear predictor
    * Link function
1. Estimate the model and report your results.
1. Interpret the results in paragraph format. This should include a discussion of your results as if you were reviewing them with fellow computational social scientists. Discuss the results using any or all of log-odds, odds, predicted probabilities, and first differences - choose what makes sense to you and provides the most value to the reader. Use graphs and tables as necessary to support your conclusions.

# Part 2: Modeling tv consumption

The [General Social Survey](http://gss.norc.org/) is a biannual survey of the American public.

> [The GSS gathers data on contemporary American society in order to monitor and explain trends and constants in attitudes, behaviors, and attributes. Hundreds of trends have been tracked since 1972. In addition, since the GSS adopted questions from earlier surveys, trends can be followed for up to 70 years. The GSS contains a standard core of demographic, behavioral, and attitudinal questions, plus topics of special interest. Among the topics covered are civil liberties, crime and violence, intergroup tolerance, morality, national spending priorities, psychological well-being, social mobility, and stress and traumatic events.](http://gss.norc.org/About-The-GSS)

In this part of the problem set, you are going to derive and estimate a series of models to explain and predict TV consumption, or the number of hours of TV watched per day. As this is an event count, you will use Poisson regression to model the response variable. `gss2006.csv` contains a subset of the 2006 survey which contains many variables you can use to construct a model.

* `tvhours` - The number of hours of TV watched per day
* `age` - Age (in years)
* `childs` - Number of children
* `educ` - Highest year of formal schooling completed
* `female` - 1 if female, 0 if male
* `grass` - 1 if respondent thinks marijuana should be legalized, 0 otherwise
* `hrsrelax` - Hours per day respondent has to relax
* `black` - 1 if respondent is black, 0 otherwise
* `social_connect` - Ordinal scale of social connectedness, with values low-moderate-high (0-1-2)
* `voted04` - 1 if respondent voted in the 2004 presidential election, 0 otherwise
* `xmovie` - 1 if respondent saw an X-rated movie in the last year, 0 otherwise
* `zodiac` - Respondent's [astrological sign](https://en.wikipedia.org/wiki/Astrological_sign)

## Estimate a regression model (3 points)

Using the other variables in the dataset, derive and estimate a multiple variable Poisson regression model of hours of TV watched.

1. Write out the three components of the GLM for your specific model of interest. This includes the
    * Probability distribution (random component)
    * Linear predictor
    * Link function
1. Estimate the model and report your results.
1. Interpret the results in paragraph format. This should include a discussion of your results as if you were reviewing them with fellow computational social scientists. Discuss the results using any or all of log-counts, predicted event counts, and first differences - choose what makes sense to you and provides the most value to the reader. Is the model over or under-dispersed? Use graphs and tables as necessary to support your conclusions.

# Submission instructions

Assignment submission will work the same as earlier assignments. Submit your work as a pull request before the start of class on Monday. Store it in the same locations as you've been using. However the format of your submission should follow the procedures outlined below.

## If you use R

Submit your assignment as a single [R Markdown document](http://rmarkdown.rstudio.com/). R Markdown is similar to Juptyer Notebooks and compiles all your code, output, and written analysis in a single reproducible file.

## If you use Python

Either:

1. Submit your assignment following the same procedures as required by Dr. Evans. Submit a Python script containing all your code, plus a Latex generated PDF document with your results and substantive analysis.
1. Submit your assignment as a single Jupyter Notebook with your code, output, and written analysis compiled there.

    